// Static shop catalog — 16 products / 5 categories / sample reviews.
// 외부 framework 앱은 그대로 import해서 사용 (DB 없음).

import type { Category, Product, Review } from './types'

export const categories: readonly Category[] = [
  { slug: 'apparel', name: 'Apparel', description: '일상에서 입을 수 있는 핵심 의류 라인.' },
  { slug: 'tech', name: 'Tech', description: '데스크 셋업과 모바일 액세서리.' },
  { slug: 'home', name: 'Home', description: '공간을 정돈하는 작은 도구.' },
  { slug: 'beauty', name: 'Beauty', description: '단단한 기초를 만드는 데일리 케어.' },
  { slug: 'sports', name: 'Sports', description: '주말 트레일을 위한 장비.' },
]

export const products: readonly Product[] = [
  {
    id: 'p-001', slug: 'oversize-tee-charcoal', category: 'apparel',
    name: '오버사이즈 티셔츠 — 차콜',
    summary: '300gsm 코튼, 박시한 핏의 데일리 티.',
    description: '두꺼운 코튼 저지로 봉제. 박시한 실루엣과 떨어지는 어깨선이 특징. 워싱 후에도 형태가 잘 유지된다.',
    priceCents: 4900, currency: 'USD', rating: 4.6, reviewCount: 248, stock: 42,
    imageColor: '#3a3a3a',
    tags: ['cotton', 'oversize', 'unisex'],
    variants: [
      { id: 'v-s', label: 'S', priceDelta: 0, stock: 8 },
      { id: 'v-m', label: 'M', priceDelta: 0, stock: 14 },
      { id: 'v-l', label: 'L', priceDelta: 0, stock: 12 },
      { id: 'v-xl', label: 'XL', priceDelta: 200, stock: 8 },
    ],
    badge: 'best',
  },
  {
    id: 'p-002', slug: 'linen-trouser-cream', category: 'apparel',
    name: '리넨 트라우저 — 크림',
    summary: '여름용 와이드 핏 리넨 팬츠.',
    description: '벨기에산 헴프 블렌드 리넨. 통기성이 좋고 자연스러운 주름을 그대로 살린 디자인.',
    priceCents: 8900, currency: 'USD', rating: 4.4, reviewCount: 87, stock: 18,
    imageColor: '#e9dfca',
    tags: ['linen', 'summer'],
    variants: [
      { id: 'v-28', label: '28', priceDelta: 0, stock: 4 },
      { id: 'v-30', label: '30', priceDelta: 0, stock: 6 },
      { id: 'v-32', label: '32', priceDelta: 0, stock: 5 },
      { id: 'v-34', label: '34', priceDelta: 0, stock: 3 },
    ],
    badge: 'new',
  },
  {
    id: 'p-003', slug: 'wool-coat-camel', category: 'apparel',
    name: '울 코트 — 카멜',
    summary: '90% 울 더블 브레스트.',
    description: '한 사이즈 위로 입어도 무겁지 않은 가벼운 멜튼 울. 안감은 비스코스.',
    priceCents: 32900, currency: 'USD', rating: 4.8, reviewCount: 53, stock: 6,
    imageColor: '#b8966a',
    tags: ['wool', 'winter', 'outerwear'],
    variants: [
      { id: 'v-s', label: 'S', priceDelta: 0, stock: 2 },
      { id: 'v-m', label: 'M', priceDelta: 0, stock: 3 },
      { id: 'v-l', label: 'L', priceDelta: 0, stock: 1 },
    ],
    badge: 'low-stock',
  },
  {
    id: 'p-004', slug: 'mech-keyboard-tkl', category: 'tech',
    name: '메카니컬 키보드 — TKL',
    summary: '핫스왑, RGB, USB-C.',
    description: '갈축 스위치 기본 장착. 키캡은 PBT 두께 1.5mm. VIA 펌웨어로 키 매핑 가능.',
    priceCents: 14900, currency: 'USD', rating: 4.7, reviewCount: 412, stock: 28,
    imageColor: '#2b2b2b',
    tags: ['keyboard', 'mech', 'hotswap'],
    variants: [
      { id: 'v-brown', label: 'Brown', priceDelta: 0, stock: 10 },
      { id: 'v-red', label: 'Red', priceDelta: 0, stock: 12 },
      { id: 'v-silent', label: 'Silent', priceDelta: 500, stock: 6 },
    ],
    badge: 'best',
  },
  {
    id: 'p-005', slug: 'usbc-hub-7in1', category: 'tech',
    name: 'USB-C 허브 7in1',
    summary: 'HDMI 4K, SD/MicroSD, PD 100W.',
    description: '알루미늄 바디. HDMI 4K@60Hz, 3× USB-A 3.0, PD 충전 패스스루.',
    priceCents: 3900, currency: 'USD', rating: 4.2, reviewCount: 1208, stock: 156,
    imageColor: '#9a9a9a',
    tags: ['hub', 'usb-c', 'travel'],
    variants: [],
  },
  {
    id: 'p-006', slug: 'noise-cancel-headphone', category: 'tech',
    name: '노이즈 캔슬링 헤드폰',
    summary: '40h 배터리, 멀티포인트.',
    description: '액티브 노이즈 캔슬링 4단계. 2개 기기 동시 연결. 케이스 포함.',
    priceCents: 24900, currency: 'USD', rating: 4.5, reviewCount: 332, stock: 41,
    imageColor: '#1c1c2b', discountPercent: 15,
    tags: ['headphone', 'anc'],
    variants: [
      { id: 'v-black', label: 'Black', priceDelta: 0, stock: 22 },
      { id: 'v-sand', label: 'Sand', priceDelta: 0, stock: 19 },
    ],
    badge: 'sale',
  },
  {
    id: 'p-007', slug: 'ceramic-mug-set', category: 'home',
    name: '세라믹 머그 4개 세트',
    summary: '350ml, 식기세척기 가능.',
    description: '베트남 핸드메이드 세라믹. 굽 부분만 무광 처리해 들 때 안정적.',
    priceCents: 4200, currency: 'USD', rating: 4.6, reviewCount: 178, stock: 89,
    imageColor: '#d9d2c5',
    tags: ['kitchen', 'mug'],
    variants: [],
  },
  {
    id: 'p-008', slug: 'desk-lamp-arc', category: 'home',
    name: '아크 데스크 램프',
    summary: '5단계 조도, USB 충전.',
    description: '알루미늄 합금. 색온도 3000~6500K 무단 조절. 5V USB-C 충전.',
    priceCents: 6900, currency: 'USD', rating: 4.3, reviewCount: 64, stock: 31,
    imageColor: '#4a4a4a',
    tags: ['lamp', 'workspace'],
    variants: [
      { id: 'v-graphite', label: 'Graphite', priceDelta: 0, stock: 17 },
      { id: 'v-white', label: 'White', priceDelta: 0, stock: 14 },
    ],
    badge: 'new',
  },
  {
    id: 'p-009', slug: 'aroma-diffuser', category: 'home',
    name: '아로마 디퓨저',
    summary: '300ml, 7색 무드 라이트.',
    description: '초음파 미스트, 8시간 인터벌 타이머. 자동 꺼짐 안전 센서 내장.',
    priceCents: 3200, currency: 'USD', rating: 4.1, reviewCount: 92, stock: 124,
    imageColor: '#ccddd6',
    tags: ['diffuser', 'wellness'],
    variants: [],
  },
  {
    id: 'p-010', slug: 'cleansing-oil', category: 'beauty',
    name: '클렌징 오일 200ml',
    summary: '저자극, 식물성 베이스.',
    description: '7가지 식물성 오일 블렌드. 메이크업과 자외선 차단제까지 한 번에 정리.',
    priceCents: 1800, currency: 'USD', rating: 4.5, reviewCount: 521, stock: 78,
    imageColor: '#e8d7c1',
    tags: ['cleanser', 'oil'],
    variants: [],
  },
  {
    id: 'p-011', slug: 'serum-vitamin-c', category: 'beauty',
    name: '비타민 C 세럼 30ml',
    summary: '15% 농도, 페룰릭 산 동반.',
    description: 'L-아스코르빅 산 15%. 진정 효과를 위해 1% 페룰릭 산 + 0.5% 비타민 E.',
    priceCents: 3400, currency: 'USD', rating: 4.7, reviewCount: 287, stock: 56,
    imageColor: '#f0c878', discountPercent: 10,
    tags: ['serum', 'brightening'],
    variants: [],
    badge: 'sale',
  },
  {
    id: 'p-012', slug: 'lip-balm-trio', category: 'beauty',
    name: '립밤 3종 세트',
    summary: '바닐라 / 민트 / 베리.',
    description: '시어버터 기반. 향이 인공적이지 않게 약하게 들어감.',
    priceCents: 1200, currency: 'USD', rating: 4.4, reviewCount: 633, stock: 240,
    imageColor: '#e0a4a8',
    tags: ['lip', 'gift'],
    variants: [],
  },
  {
    id: 'p-013', slug: 'trail-shoe-x1', category: 'sports',
    name: '트레일 러닝화 X1',
    summary: '비브람 아웃솔, 방수.',
    description: '비브람 메가그립 아웃솔. 고어텍스 인비저블 멤브레인으로 가벼운 방수.',
    priceCents: 14900, currency: 'USD', rating: 4.6, reviewCount: 198, stock: 22,
    imageColor: '#6e7c4a',
    tags: ['running', 'trail'],
    variants: [
      { id: 'v-260', label: '260mm', priceDelta: 0, stock: 4 },
      { id: 'v-265', label: '265mm', priceDelta: 0, stock: 6 },
      { id: 'v-270', label: '270mm', priceDelta: 0, stock: 7 },
      { id: 'v-275', label: '275mm', priceDelta: 0, stock: 5 },
    ],
    badge: 'best',
  },
  {
    id: 'p-014', slug: 'water-bottle-700', category: 'sports',
    name: '스테인레스 보틀 700ml',
    summary: '24시간 보냉, 12시간 보온.',
    description: '이중 단열 스테인레스. 잠금식 뚜껑, 광구 디자인으로 얼음 투입 쉬움.',
    priceCents: 2800, currency: 'USD', rating: 4.5, reviewCount: 401, stock: 167,
    imageColor: '#3a5a7c',
    tags: ['hydration', 'outdoor'],
    variants: [
      { id: 'v-navy', label: 'Navy', priceDelta: 0, stock: 60 },
      { id: 'v-olive', label: 'Olive', priceDelta: 0, stock: 55 },
      { id: 'v-coral', label: 'Coral', priceDelta: 0, stock: 52 },
    ],
  },
  {
    id: 'p-015', slug: 'yoga-mat-cork', category: 'sports',
    name: '코르크 요가 매트',
    summary: '6mm, 자연 항균.',
    description: '코르크 표면 + TPE 베이스. 미끄러짐 방지, 가벼운 항균.',
    priceCents: 4900, currency: 'USD', rating: 4.3, reviewCount: 142, stock: 38,
    imageColor: '#c79a6b',
    tags: ['yoga', 'eco'],
    variants: [],
    badge: 'new',
  },
  {
    id: 'p-016', slug: 'compression-tights', category: 'sports',
    name: '컴프레션 타이즈',
    summary: '근막 압박, 자외선 차단 50+.',
    description: '나일론 80% + 스판덱스 20%. 무릎과 종아리에 단계적 압박.',
    priceCents: 5900, currency: 'USD', rating: 4.2, reviewCount: 76, stock: 29,
    imageColor: '#1f1f1f',
    tags: ['running', 'baselayer'],
    variants: [
      { id: 'v-s', label: 'S', priceDelta: 0, stock: 9 },
      { id: 'v-m', label: 'M', priceDelta: 0, stock: 11 },
      { id: 'v-l', label: 'L', priceDelta: 0, stock: 9 },
    ],
  },
]

export const reviews: readonly Review[] = [
  { id: 'r-001', productId: 'p-001', author: '서지운', rating: 5, title: '핏이 정말 좋아요', body: '170cm 보통 체형인데 M 입었습니다. 어깨 떨어짐이 자연스럽고 옆선이 안 무너집니다.', createdAt: Date.UTC(2026, 4, 10), helpfulCount: 23 },
  { id: 'r-002', productId: 'p-001', author: '김도현', rating: 4, title: '두꺼운 만큼 무게감', body: '겨울 레이어링용으로는 베스트, 한여름엔 좀 더울 수 있습니다.', createdAt: Date.UTC(2026, 3, 22), helpfulCount: 12 },
  { id: 'r-003', productId: 'p-004', author: 'Min-ji L.', rating: 5, title: '핫스왑이 진리', body: '갈축 → 청축 변경 5분컷. RGB도 조작 직관적.', createdAt: Date.UTC(2026, 5, 1), helpfulCount: 41 },
  { id: 'r-004', productId: 'p-006', author: '이성호', rating: 5, title: '출퇴근 필수템', body: 'ANC 한 단계만 켜도 지하철 소음 거의 사라집니다. 멀티포인트 안정적.', createdAt: Date.UTC(2026, 4, 28), helpfulCount: 37 },
  { id: 'r-005', productId: 'p-011', author: '박서연', rating: 5, title: '톤업이 진짜 됨', body: '아침에 1방울만 발라도 한 시간 뒤에 차이 보입니다.', createdAt: Date.UTC(2026, 5, 5), helpfulCount: 58 },
  { id: 'r-006', productId: 'p-013', author: 'Junho', rating: 4, title: '바위 위에서도 안정', body: '비 오는 산길에서도 미끄러짐 거의 없음. 사이즈는 0.5 크게.', createdAt: Date.UTC(2026, 3, 15), helpfulCount: 19 },
]

export const SHIPPING_FEE_CENTS = 500
export const FREE_SHIPPING_THRESHOLD_CENTS = 10000
export const TAX_RATE = 0.1
